package com.example.todolist.Server;

public enum Status {
    LOGIN_SUCCESS, USERNAME_NOT_FOUND, INCORRECT_PASSWORD, ACCOUNT_CREATED_SUCCESSFULLY, ACCOUNT_CREATION_FAILED,
    ACCOUNT_UPDATED_SUCCESSFULLY, ACCOUNT_UPDATE_FAILED, ACCOUNT_DELETION_FAILED, ACCOUNT_DELETED_SUCCESSFULLY
}